# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('gif_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date published', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=False)),
                ('publication_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RssUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_url', models.URLField(verbose_name='Rss source')),
                ('rss_name', models.CharField(max_length=200, verbose_name='Name')),
                ('active', models.BooleanField(default=0)),
                ('last_post', models.DateTimeField(blank=True, null=True, verbose_name='Last checked post')),
            ],
        ),
        migrations.AddField(
            model_name='gif',
            name='publication_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_blog.Publication'),
        ),
    ]
