# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssurl',
            name='rss_url',
            field=models.URLField(unique=True, verbose_name='Rss source'),
        ),
    ]
